### PR TITLE
Add GPX export support

### PR DESCRIPTION
**Pull request by lct8712**
Support export data as gpx files. All files ziped as Gpx.zip.

Each Tile consists of 8192*8192 pixels. By utilizing the latitude and longitude of the bounds for each Tile, we can calculate the corresponding latitude and longitude for each pixel within the Tile, proportionally. This allows us to obtain the latitude and longitude points for each Tile using the `LngLatToGlobalXY` function.

Creating a GPX file from a list of latitude and longitude points is a bit complex since the original image data doesn't include timestamps, making it impossible to reconstruct the GPX path. To address this, I attempt to reconstruct the original path by finding the closest point for each given point using the `sortFilledList` function.

Furthermore, to prevent abrupt jumps in the GPX point connections or to avoid excessively large GPX files, I split each Tile into multiple GPX files.

Finally, all the GPX files are packaged into Gpx.zip for downloading using the `dumpGpx` function.

### CODE REVIEW

**Comment by CaviarChen** [comment]
Hey, this is awesome! thank you so much!
However, I'm kinda busy recently and I'll aim to finish reviewing this in a week or two.
In the meantime, could you try to solve some hygiene issues and make it pass our CI?
Some things I noticed:
- remove files changed under `frontend`. I don't think this PR touches things there.
- remove `package-lock.json`, we use yarn instead of npm.
- changes to `editor/yarn.lock` seems related to switching npm.
- make sure code is formated correctly, you can do this by running `yarn autofix`

**Comment by lct8712** [comment]
It seems the issues have been fixed.
I am an Android developer and not very familiar with frontend technologies, if there are any further issues, please leave a message.

**Comment by CaviarChen** [comment]
Thank you so much! No worries, I can also clean up the PR for you (just need a bit of time)

**Comment by CaviarChen** [comment]
Hey! Thank you again and sorry for the long wait.
I modified your code a bit, and you can find the modified version here: https://github.com/CaviarChen/fog-machine/tree/pr-101
If you are happy with it, could you merge it to your branch?

Mostly, things I did are:
1. Code clean up and refactor.
2. Move most code to `GpxExport.ts` because for an experimental feature, having all code in a single place feels better.
3. Drop the timestamp. It is valid for a gpx file to not have timestamp and having wrong information is wrose than not having it.

For an experimental feature, the current state is pretty good, I'm ok with merging it before making it perfect. So I left a lot of TODOs in the code instead of review comments. We could always improve it later. 
Among all these TODOs, I believe https://github.com/CaviarChen/fog-machine/blob/pr-101/editor/src/MainMenu.tsx#L205-L208 is the most important one. The current version is not user friendly enough and may freeze the browser.

**Review by CaviarChen — APPROVED** [review]

**Pull request merged**
